plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
}

group = 'org.leralix.tan-api'
version = '0.8.0'

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven {
        name = "GitHubPackages"
        url = "https://maven.pkg.github.com/SteelDominion/Towns-and-Nations"
        credentials {
            username = System.getenv("GITHUB_USER")
            password = System.getenv("GITHUB_TOKEN")
        }
    }
    maven {
        name = "spigot-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven {
        name = "local"
        url = uri("${rootDir}/../SphereLib/build/repo")
    }
}

javadoc {
    options.overview = "src/main/javadoc/overview.html"
}

dependencies {
    compileOnly 'org.spigotmc:spigot-api:1.20.2-R0.1-SNAPSHOT'
    compileOnly 'io.github.leralix:sphere-lib:0.4.6'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = 'tan-api'
            from components.java

            pom {
                name = "Towns and Nations API"
                description = "Public API for Towns and Nations plugin"
                url = "https://github.com/SteelDominion/Towns-and-Nations"
                licenses {
                    license {
                        name = "GNU General Public License v3.0"
                        url = "https://www.gnu.org/licenses/gpl-3.0.html"
                        distribution = "https://www.gnu.org/licenses/gpl-3.0.html"
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/SteelDominion/Towns-and-Nations.git'
                    developerConnection = 'scm:git:ssh://github.com/SteelDominion/Towns-and-Nations.git'
                    url = 'https://github.com/SteelDominion/Towns-and-Nations'
                }
            }
        }
    }
    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/SteelDominion/Towns-and-Nations")
            credentials {
                username = System.getenv("GITHUB_ACTOR")
                password = System.getenv("GITHUB_TOKEN")
            }
        }
    }
}
